#' scr9_1
#' @description
#' The solution to the exercise 9_1 for Rizzo's Book.
#'
#' Repeat Example 9.1 for the target distribution Rayleigh(σ = 2).
#' Compare the performance of the Metropolis-Hastings sampler for Example 9.1
#' and this problem. In particular, what diﬀerences are obvious from the
#' plot corresponding to Figure 9.1?
#'
#' @references Maria L. Rizzo. (2016). Statistical computing with r.
#'
#' @param m a number indicating the iteration numbers. Defaults to 10000.
#' @param sigma a number indicating the sigma parameter related to Rayleigh distribution.
#'
#' @return plot showing part of a chain generated by a Metropolis-Hastings sampler
#' for the target Rayleigh distribution with σ = 2.
#' @export
#'
#' @examples scr9_1()
#'
#'
#'
scr9_1 <- function(m = 10000, sigma = 2){
  f <- function(x, sigma) {
    if (any(x < 0)) return (0)
    stopifnot(sigma > 0)
    return((x / sigma^2) * exp(-x^2 / (2*sigma^2)))
  }

  rRayleigh <- function(s){
    u <- runif(1)
    s * sqrt(-2 * log(1-u))
  }

  x <- numeric(m)
  x[1] <- rRayleigh(2)
  k <- 0
  u <- runif(m)

  for (i in 2:m) {
    xt <- x[i-1]
    y <- rRayleigh(xt)
    num <- f(y, sigma) * f(xt, y)
    den <- f(xt, sigma) * f(y, xt)
    if (u[i] <= num/den) x[i] <- y else {
      x[i] <- xt
      k <- k+1     #y is rejected
    }
  }

  index <- 5000:5500
  y1 <- x[index]
  plot(index, y1, type="l",
       main=paste0("Metropolis-Hastings sampler with sigma = ", sigma), ylab="x")
}
